# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YieldzoneAdDemo_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
 # use_frameworks!
pod 'YieldzoneAdSDK','3.1.0'
 # pod 'YieldzoneAdSDK',:path => '../../YieldzoneAdSDK2'
  # Pods for SparkXAdDemo-Swift


end
