# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

 platform :ios, '9.0'

target 'YieldzoneAdDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

pod 'YieldzoneAdSDK','3.1.0'
#pod 'YieldzoneAdSDK',:path => '../../YieldzoneAdSDK2'
#pod 'YieldzoneAdSDK',:path => '../../YieldzoneAdSDK-3.0.0'
  target 'YieldzoneAdDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YieldzoneAdDemoUITests' do
    # Pods for testing
  end

end
